<?php

require_once '..\..\DAO\ChamadoDAO.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 12:48:47.
 */
class ChamadoDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ChamadoDAO
     */
    
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ChamadoDAO();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    
    protected function tearDown() {
        
    }

    /**
     * @covers ChamadoDAO
     * @todo   Implement testVerificar().
     */
    public function testVerificar() {
        // Remove the following lines when you implement this test.
        $this->assertNotNull($this->object);
    }

}
