<?php

require_once '..\..\DAO\ComentarioDAO.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 14:49:23.
 */
class ComentarioDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ComentarioDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ComentarioDAO();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ComentarioDAO
     * @todo   Implement testVerificarComentario().
     */
    public function testVerificarComentario() {
        // Remove the following lines when you implement this test.
        $this->assertNotNull($this->object);
    }

    

}
