<?php
require_once "../../controller/StatusCtrl.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-29 at 03:23:22.
 */
class StatusCtrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var StatusCtrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StatusCtrl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers StatusCtrl::insStatus
     * @todo   Implement testInsStatus().
     */
    public function testInsStatus() {
        $resultado = $this->object->insStatus(1, "Em Andamento");
        $this->assertEquals(true, $resultado, "Impossível inserir status!");
    }

   

    /**
     * @covers StatusCtrl::listaStatus
     * @todo   Implement testListaStatus().
     */
    public function testListaStatus() {
       $resultado = $this->object->listaStatus();
       foreach($resultado as $row){
           $this->assertArrayHasKey("cod", $row, "Impossivel retornar todos os status");
           $this->assertArrayHasKey("descricao", $row, "Impossivel retornar todos os status");
       }
       
    }

    /**
     * @covers StatusCtrl::obterStatus_Especifico
     * @todo   Implement testObterStatus_Especifico().
     */
    public function testObterStatus_Especifico() {
       $resultado = $this->object->obterStatus_Especifico(1);
        if($resultado!=false)
           $resultado = true;
       $this->assertEquals(true, $resultado, "A obtenção do usuaŕio falhou!");
    }

    /**
     * @covers StatusCtrl::alteraStatus
     * @todo   Implement testAlteraStatus().
     */
    public function testAlteraStatus() {
        $resultado = $this->object->alteraStatus(1, "Em Espera", 1);
        $this->assertTrue (true, $resultado, "impossivel alterar status");
    }
    
     /**
     * @covers StatusCtrl::delStatus
     * @todo   Implement testDelStatus().
     */
    
    public function testDelStatus() {
       $resultado = $this->object->delStatus(2);
       $this->assertTrue(true, $resultado, "Impossivel deletar status!");
    }

}
