<?php

require_once "../../controller/UsuarioCtrl.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-27 at 19:02:09.
 */
class UsuarioCtrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UsuarioCtrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UsuarioCtrl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers UsuarioCtrl::insUsuario
     * @todo   Implement testInsUsuario().
     */
    public function testInsUsuario() {
        $resultado = $this->object->insUsuario("lucascouto", "12345", "meuemail@gmail.com", "Lucas Couto", 100112048, NULL);
        $this->assertEquals(true, $resultado, "A inserção do usuário no BD falhou!");
    }

    /**
     * @covers UsuarioCtrl::delUsuario
     * @todo   Implement testDelUsuario().
     */
    public function testDelUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UsuarioCtrl::listaUsuario
     * @todo   Implement testListaUsuario().
     */
    public function testListaUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UsuarioCtrl::alteraUsuario
     * @todo   Implement testAlteraUsuario().
     */
    public function testAlteraUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UsuarioCtrl::obterUsuario_Especifico
     * @todo   Implement testObterUsuario_Especifico().
     */
    public function testObterUsuario_Especifico() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UsuarioCtrl::getNumCols
     * @todo   Implement testGetNumCols().
     */
    public function testGetNumCols() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
