//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_EFRwoUmKEeKu29KVoS-SOg,_FZ72cUmKEeKu29KVoS-SOgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Iteração da Fase de Concepção_D100499C_dbed18e0_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOgActivity"]="./../../Help_Desk/deliveryprocesses/resources/process_HelpDesk_E635A235_e635a235_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_0XBLMUmNEeKOcvRWZE27NA,_Aj7M8UmOEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Integrar Módulos_F1B7CEFC_e192a197_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_xfSJEUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Iteração da Fase de Construção 2_34506F94_8f13ae2_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_EFRwoUmKEeKu29KVoS-SOgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Concepção_625BEF67_789010f0_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Construção_50FAE971_672f0afa_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpg,_0VjdgUmLEeKdza9-gkYWpg,_2bvt8UmLEeKdza9-gkYWpgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Activity 1_38A4ECD6_2d08e584_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_0XBLMUmNEeKOcvRWZE27NA,__2jJk0mNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Desenvolver um Incremento da Solução_D6D414D7_c6aee772_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_EFRwoUmKEeKu29KVoS-SOg,_FZ72cUmKEeKu29KVoS-SOg,_HnHfsUmKEeKu29KVoS-SOgActivity"]="./../../Help_Desk/deliveryprocesses/resources/p_4B782661_f2252d95_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_0XBLMUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Iteração da Fase de Construção 3_C7B1DF9_e11be947_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_xfSJEUmNEeKOcvRWZE27NA,_-h5q00mNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Desenvolver um Incremento da Solução_4BCDD096_c61993cc_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_un2o8UmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Iteração da Fase de Construção 1_E7E1EED2_bc82ba20_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_rOxNQUmNEeKOcvRWZE27NA,_HmHdUUmOEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Avaliar Resultados_E5BF6C01_664eec54_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpg,_0VjdgUmLEeKdza9-gkYWpg,_NjtIAUmMEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Plano de Tempo_F6D2F543_eb36edf1_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpg,_0VjdgUmLEeKdza9-gkYWpg,_47-PAUmLEeKdza9-gkYWpgActivity"]="./../../Help_Desk/deliveryprocesses/resources/ahah_18043845_c6830f3_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Elaboração_40A22EC4_56d6504d_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpg,_0VjdgUmLEeKdza9-gkYWpg,_L98rIUmMEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Desenvolver a Arquitetura_4B6AFCF1_3fcef59f_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_0XBLMUmNEeKOcvRWZE27NA,__2jJlUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Testar Solução_43F30D1B_33cddfb6_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_EFRwoUmKEeKu29KVoS-SOg,_FZ72cUmKEeKu29KVoS-SOg,_I4xfYUmLEeKzbN0QdwCHdgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Identificar e Refinar os Requisitos_9A93AA4A_4140b17e_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_zJ0qMUmLEeKdza9-gkYWpg,_0VjdgUmLEeKdza9-gkYWpgActivity"]="./../../Help_Desk/deliveryprocesses/resources/Iteração da Fase de Elaboração_F4FA50B9_d4ac585a_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_xfSJEUmNEeKOcvRWZE27NA,_-h5q1UmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Testar Solução_B8ECC8DA_33388c10_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_un2o8UmNEeKOcvRWZE27NA,_3rNyIknVEeKxYpjLfq5O3AActivity"]="./../../Help_Desk/deliveryprocesses/resources/Desenvolver um Incremento da Solução_D9245E2C_9de746a0_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_rOxNQUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Transição_D3541D76_e9883eff_Activity.jpeg"
contentPage.processPage.imageFiles["_AhEDAUmKEeKu29KVoS-SOg,_o6lkIUmNEeKOcvRWZE27NA,_un2o8UmNEeKOcvRWZE27NA,_8shdkUmNEeKOcvRWZE27NAActivity"]="./../../Help_Desk/deliveryprocesses/resources/Testar Solução_47E25360_ca53bd4_Activity.jpeg"
contentPage.processPage.elementUrls["_hmoykknTEeK1i6L3TaQ98w"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_A29A0D82.html"];
contentPage.processPage.elementUrls["_3rNLEUnVEeKxYpjLfq5O3A"] = ["Implementar a Solução","Help_Desk/deliveryprocesses/implement_solution_B15092AD.html"];
contentPage.processPage.elementUrls["_XMhcakmMEeKOcvRWZE27NA"] = ["Descrever a Arquitetura","Help_Desk/deliveryprocesses/outline_the_architecture_5345A8F8.html"];
contentPage.processPage.elementUrls["_tYyK8knTEeKRYqO7-cZuww"] = ["Executar os Testes","Help_Desk/deliveryprocesses/run_tests_C50A9287.html"];
contentPage.processPage.elementUrls["_zLzf0kmOEeKOcvRWZE27NA"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_EA9A4119.html"];
contentPage.processPage.elementUrls["_JfuDoknYEeK7uPdJ1lPx3Q"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_7643055F.html"];
contentPage.processPage.elementUrls["_esu680mLEeKdza9-gkYWpg"] = ["Planejar o Projeto","Help_Desk/deliveryprocesses/plan_the_project_7BFECED2.html"];
contentPage.processPage.elementUrls["_aOpxA0nWEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_E03C9C06.html"];
contentPage.processPage.elementUrls["_3rNyIEnVEeKxYpjLfq5O3A"] = ["Implementar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/impl_developer_tests_DFED6A06.html"];
contentPage.processPage.elementUrls["_H-NGMUnbEeK7uPdJ1lPx3Q"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_D93E0347.html"];
contentPage.processPage.elementUrls["_JfuDoEnYEeK7uPdJ1lPx3Q"] = ["Caso de Teste","Help_Desk/deliveryprocesses/test_case_7D0C1139.html"];
contentPage.processPage.elementUrls["_uX_d0EnWEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_F140249E.html"];
contentPage.processPage.elementUrls["_CyunMEnYEeKlhdW4xK3Y2Q"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_75A2AC3.html"];
contentPage.processPage.elementUrls["_fi7bwEmOEeKOcvRWZE27NA"] = ["Analista","Help_Desk/deliveryprocesses/analyst_8AB59CDC.html"];
contentPage.processPage.elementUrls["_3rOZMknVEeKxYpjLfq5O3A"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_EB6BE6A8.html"];
contentPage.processPage.elementUrls["_Cbiu4UnbEeK7uPdJ1lPx3Q"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_4BC498D.html"];
contentPage.processPage.elementUrls["_6e1JQknVEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_EDE2EC42.html"];
contentPage.processPage.elementUrls["_AhEDAUmKEeKu29KVoS-SOg"] = ["process_HelpDesk","Help_Desk/deliveryprocesses/process_HelpDesk_E635A235.html"];
contentPage.processPage.elementUrls["_zLzf00mOEeKOcvRWZE27NA"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_537416DE.html"];
contentPage.processPage.elementUrls["_3rNyIknVEeKxYpjLfq5O3A"] = ["Desenvolver um Incremento da Solução","Help_Desk/deliveryprocesses/Desenvolver um Incremento da Solução_D9245E2C.html"];
contentPage.processPage.elementUrls["_cWBiQEmLEeKdza9-gkYWpg"] = ["Encontrar e Descrever os Requisitos","Help_Desk/deliveryprocesses/find_and_outline_requirements_B21A8F1A.html"];
contentPage.processPage.elementUrls["_aOpxBEnWEeKxYpjLfq5O3A"] = ["Testador","Help_Desk/deliveryprocesses/tester_42BDB43A.html"];
contentPage.processPage.elementUrls["_nSC5YUnXEeKxYpjLfq5O3A"] = ["Implementação","Help_Desk/deliveryprocesses/implementation_CC765B35.html"];
contentPage.processPage.elementUrls["_uTdGoUnXEeKxYpjLfq5O3A"] = ["Caso de Teste","Help_Desk/deliveryprocesses/test_case_BD185B8A.html"];
contentPage.processPage.elementUrls["__2jJlUmNEeKOcvRWZE27NA"] = ["Testar Solução","Help_Desk/deliveryprocesses/Testar Solução_43F30D1B.html"];
contentPage.processPage.elementUrls["_XUcCoknWEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_2FD797A.html"];
contentPage.processPage.elementUrls["_MVPfQUnYEeK7uPdJ1lPx3Q"] = ["Registro de Teste","Help_Desk/deliveryprocesses/test_log_1ED0495B.html"];
contentPage.processPage.elementUrls["_9FXts0nVEeKxYpjLfq5O3A"] = ["Testador","Help_Desk/deliveryprocesses/tester_86C3F186.html"];
contentPage.processPage.elementUrls["_uX_d1EnWEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_B5D206BD.html"];
contentPage.processPage.elementUrls["_Aw2OAEnjEeKJs9Z4aVEEmA"] = ["Marco da Fase de Concepção","Help_Desk/deliveryprocesses/Marco da Fase de Concepção_FD2BC53A.html"];
contentPage.processPage.elementUrls["_tYyK8EnTEeKRYqO7-cZuww"] = ["Implementar os Scripts de Teste","Help_Desk/deliveryprocesses/implement_test_scripts_CBD39E61.html"];
contentPage.processPage.elementUrls["_K_nlkEnXEeKxYpjLfq5O3A"] = ["Plano de Projeto","Help_Desk/deliveryprocesses/project_plan_DEC7620E.html"];
contentPage.processPage.elementUrls["_fi7bwkmOEeKOcvRWZE27NA"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_83EC9102.html"];
contentPage.processPage.elementUrls["_aOpxAUnWEeKxYpjLfq5O3A"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_88C9B22B.html"];
contentPage.processPage.elementUrls["_uD_EEEnTEeKRYqO7-cZuww"] = ["Implementar os Scripts de Teste","Help_Desk/deliveryprocesses/implement_test_scripts_ECC7A0D2.html"];
contentPage.processPage.elementUrls["_rqS98EnVEeKGP5MA8koQEg"] = ["Analista","Help_Desk/deliveryprocesses/analyst_60DDA3A5.html"];
contentPage.processPage.elementUrls["_EFRwoUmKEeKu29KVoS-SOg"] = ["Concepção","Help_Desk/deliveryprocesses/Concepção_625BEF67.html"];
contentPage.processPage.elementUrls["_rnsn0knTEeKRYqO7-cZuww"] = ["Executar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/run_developer_tests_4C7C870F.html"];
contentPage.processPage.elementUrls["_xfSJEUmNEeKOcvRWZE27NA"] = ["Iteração da Fase de Construção 2","Help_Desk/deliveryprocesses/Iteração da Fase de Construção 2_34506F94.html"];
contentPage.processPage.elementUrls["_KB41M0nbEeK7uPdJ1lPx3Q"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_99BA1458.html"];
contentPage.processPage.elementUrls["_rqS98knVEeKGP5MA8koQEg"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_5A1497CB.html"];
contentPage.processPage.elementUrls["_6e1JQUnVEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_FF49D82C.html"];
contentPage.processPage.elementUrls["_rnsn00nTEeKRYqO7-cZuww"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_B5565CD4.html"];
contentPage.processPage.elementUrls["_I2T5QEnjEeKJs9Z4aVEEmA"] = ["Marco da Fase de Construção","Help_Desk/deliveryprocesses/Marco da Fase de Construção_F56E1B61.html"];
contentPage.processPage.elementUrls["_MsEAQEmKEeKu29KVoS-SOg"] = ["Planejar o Projeto","Help_Desk/deliveryprocesses/plan_the_project_948E0AD1.html"];
contentPage.processPage.elementUrls["_nSC5YEnXEeKxYpjLfq5O3A"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_C1D87B25.html"];
contentPage.processPage.elementUrls["_zLzf1EmOEeKOcvRWZE27NA"] = ["Testador","Help_Desk/deliveryprocesses/tester_B5F52F12.html"];
contentPage.processPage.elementUrls["_fi7bw0mOEeKOcvRWZE27NA"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_ECC666C7.html"];
contentPage.processPage.elementUrls["_b6OFgEnXEeKxYpjLfq5O3A"] = ["Lista de Riscos","Help_Desk/deliveryprocesses/lista_riscos_4A20D40B.html"];
contentPage.processPage.elementUrls["_PbIHkUnXEeKxYpjLfq5O3A"] = ["Modelo de Caso de Uso","Help_Desk/deliveryprocesses/uc_model_49730CDD.html"];
contentPage.processPage.elementUrls["_MVPfQknYEeK7uPdJ1lPx3Q"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_D695D71.html"];
contentPage.processPage.elementUrls["_H-NGMknbEeK7uPdJ1lPx3Q"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_C7D7175D.html"];
contentPage.processPage.elementUrls["_wwa1IEnTEeKRYqO7-cZuww"] = ["Projetar a Solução","Help_Desk/deliveryprocesses/design_solution_4C8790E9.html"];
contentPage.processPage.elementUrls["_aOpxAEnWEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_7E2BD21B.html"];
contentPage.processPage.elementUrls["_uX_d00nWEeKxYpjLfq5O3A"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_5350EE89.html"];
contentPage.processPage.elementUrls["_rOxNQUmNEeKOcvRWZE27NA"] = ["Transição","Help_Desk/deliveryprocesses/Transição_D3541D76.html"];
contentPage.processPage.elementUrls["_tUD-0EnaEeK7uPdJ1lPx3Q"] = ["Avaliar Resultados Obtidos e Experiências","Help_Desk/deliveryprocesses/avaliar_resultados_57803D9F.html"];
contentPage.processPage.elementUrls["_nt6jwEncEeKkmalgrXV56Q"] = ["Software","Help_Desk/deliveryprocesses/software_6574E16B.html"];
contentPage.processPage.elementUrls["_47-PAUmLEeKdza9-gkYWpg"] = ["Mitigar Riscos","Help_Desk/deliveryprocesses/ahah_18043845.html"];
contentPage.processPage.elementUrls["_fITyIEnXEeKxYpjLfq5O3A"] = ["Caderno de Arquitetura","Help_Desk/deliveryprocesses/architecture_notebook_C99420C6.html"];
contentPage.processPage.elementUrls["_XUcCoUnWEeKxYpjLfq5O3A"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_14646564.html"];
contentPage.processPage.elementUrls["_j4lAAEnTEeK1i6L3TaQ98w"] = ["Executar os Testes","Help_Desk/deliveryprocesses/run_tests_F445E676.html"];
contentPage.processPage.elementUrls["_XUcCoEnWEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_9C68554.html"];
contentPage.processPage.elementUrls["_o6lkIUmNEeKOcvRWZE27NA"] = ["Construção","Help_Desk/deliveryprocesses/Construção_50FAE971.html"];
contentPage.processPage.elementUrls["_LD1hwknYEeK7uPdJ1lPx3Q"] = ["Implementação","Help_Desk/deliveryprocesses/implementation_6085BE5B.html"];
contentPage.processPage.elementUrls["_6e1wUEnVEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_2DE6AF85.html"];
contentPage.processPage.elementUrls["_NjtIAUmMEeKOcvRWZE27NA"] = ["Plano de Tempo","Help_Desk/deliveryprocesses/Plano de Tempo_F6D2F543.html"];
contentPage.processPage.elementUrls["_G4AZgEnjEeKJs9Z4aVEEmA"] = ["Marco da Fase de Elaboração","Help_Desk/deliveryprocesses/Marco da Fase de Elaboração_6EBB37A7.html"];
contentPage.processPage.elementUrls["_fi7bwUmOEeKOcvRWZE27NA"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_95537CEC.html"];
contentPage.processPage.elementUrls["_uX_d0knWEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_EA7718C4.html"];
contentPage.processPage.elementUrls["_IGow0EnYEeK7uPdJ1lPx3Q"] = ["Construção","Help_Desk/deliveryprocesses/build_9B406993.html"];
contentPage.processPage.elementUrls["_2bvt8UmLEeKdza9-gkYWpg"] = ["Identificar e Analisar Riscos","Help_Desk/deliveryprocesses/Activity 1_38A4ECD6.html"];
contentPage.processPage.elementUrls["_FZ72cUmKEeKu29KVoS-SOg"] = ["Iteração da Fase de Concepção","Help_Desk/deliveryprocesses/Iteração da Fase de Concepção_D100499C.html"];
contentPage.processPage.elementUrls["_Cbiu4knbEeK7uPdJ1lPx3Q"] = ["Testador","Help_Desk/deliveryprocesses/tester_F3555DA3.html"];
contentPage.processPage.elementUrls["_XUcCpEnWEeKxYpjLfq5O3A"] = ["Testador","Help_Desk/deliveryprocesses/tester_CE586773.html"];
contentPage.processPage.elementUrls["_rnsn0UnTEeKRYqO7-cZuww"] = ["Implementar a Solução","Help_Desk/deliveryprocesses/implement_solution_5DE372F9.html"];
contentPage.processPage.elementUrls["_KB41MknbEeK7uPdJ1lPx3Q"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_30E03E93.html"];
contentPage.processPage.elementUrls["_Cbiu4EnbEeK7uPdJ1lPx3Q"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_FA1E697D.html"];
contentPage.processPage.elementUrls["_YdU9UUnWEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_AD8E00B0.html"];
contentPage.processPage.elementUrls["_wwbcM0nTEeKRYqO7-cZuww"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_D3C8D161.html"];
contentPage.processPage.elementUrls["_l6eXkEnZEeK7uPdJ1lPx3Q"] = ["Analisar Riscos","Help_Desk/deliveryprocesses/analise_riscos_DCE6F110.html"];
contentPage.processPage.elementUrls["_YdU9UknWEeKxYpjLfq5O3A"] = ["Testador","Help_Desk/deliveryprocesses/tester_9C2714C6.html"];
contentPage.processPage.elementUrls["_JfuDoUnYEeK7uPdJ1lPx3Q"] = ["Registro de Teste","Help_Desk/deliveryprocesses/test_log_87A9F149.html"];
contentPage.processPage.elementUrls["_9FXtsknVEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_1DEA1BC1.html"];
contentPage.processPage.elementUrls["_fi7bxUmOEeKOcvRWZE27NA"] = ["Testador","Help_Desk/deliveryprocesses/tester_59E55F0B.html"];
contentPage.processPage.elementUrls["_zJ0qMUmLEeKdza9-gkYWpg"] = ["Elaboração","Help_Desk/deliveryprocesses/Elaboração_40A22EC4.html"];
contentPage.processPage.elementUrls["_IGow0knYEeK7uPdJ1lPx3Q"] = ["Implementação","Help_Desk/deliveryprocesses/implementation_94775DB9.html"];
contentPage.processPage.elementUrls["_LD1hwUnYEeK7uPdJ1lPx3Q"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_71ECAA45.html"];
contentPage.processPage.elementUrls["_LcLFsEmKEeKu29KVoS-SOg"] = ["Definir a Visão","Help_Desk/deliveryprocesses/define_vision_B999C59E.html"];
contentPage.processPage.elementUrls["_uX_d0UnWEeKxYpjLfq5O3A"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_FBDE04AE.html"];
contentPage.processPage.elementUrls["_XUcCo0nWEeKxYpjLfq5O3A"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_6BD74F3F.html"];
contentPage.processPage.elementUrls["_KB41NEnbEeK7uPdJ1lPx3Q"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_FC3B2C8C.html"];
contentPage.processPage.elementUrls["_TMG-gEnaEeK7uPdJ1lPx3Q"] = ["Planejar o Tempo","Help_Desk/deliveryprocesses/planejar_tempo_143E557D.html"];
contentPage.processPage.elementUrls["_Fc8DUUnbEeK7uPdJ1lPx3Q"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_481DD6CA.html"];
contentPage.processPage.elementUrls["_fi7bxEmOEeKOcvRWZE27NA"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_4F477EFB.html"];
contentPage.processPage.elementUrls["_YdUWQEnWEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_AAA00CC2.html"];
contentPage.processPage.elementUrls["_H-NGMEnbEeK7uPdJ1lPx3Q"] = ["Analista","Help_Desk/deliveryprocesses/analyst_CEA02337.html"];
contentPage.processPage.elementUrls["_rnsn0EnTEeKRYqO7-cZuww"] = ["Implementar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/impl_developer_tests_534592E9.html"];
contentPage.processPage.elementUrls["_zLzf0UmOEeKOcvRWZE27NA"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_FC012D03.html"];
contentPage.processPage.elementUrls["_3rOZMEnVEeKxYpjLfq5O3A"] = ["Executar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/run_developer_tests_F234F282.html"];
contentPage.processPage.elementUrls["_Aj7M8UmOEeKOcvRWZE27NA"] = ["Integrar Módulos","Help_Desk/deliveryprocesses/Integrar Módulos_F1B7CEFC.html"];
contentPage.processPage.elementUrls["_0XBLMUmNEeKOcvRWZE27NA"] = ["Iteração da Fase de Construção 3","Help_Desk/deliveryprocesses/Iteração da Fase de Construção 3_C7B1DF9.html"];
contentPage.processPage.elementUrls["_Fc8DUknbEeK7uPdJ1lPx3Q"] = ["Stakeholder","Help_Desk/deliveryprocesses/stakeholder_36B6EAE0.html"];
contentPage.processPage.elementUrls["_YdU9UEnWEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_A2F020A0.html"];
contentPage.processPage.elementUrls["_HmHdUUmOEeKOcvRWZE27NA"] = ["Avaliar Resultados","Help_Desk/deliveryprocesses/Avaliar Resultados_E5BF6C01.html"];
contentPage.processPage.elementUrls["_zLzf0EmOEeKOcvRWZE27NA"] = ["Analista","Help_Desk/deliveryprocesses/analyst_F1634CF3.html"];
contentPage.processPage.elementUrls["_KB41MUnbEeK7uPdJ1lPx3Q"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_42472A7D.html"];
contentPage.processPage.elementUrls["_wwbcMEnTEeKRYqO7-cZuww"] = ["Implementar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/impl_developer_tests_71B80776.html"];
contentPage.processPage.elementUrls["_0VjdgUmLEeKdza9-gkYWpg"] = ["Iteração da Fase de Elaboração","Help_Desk/deliveryprocesses/Iteração da Fase de Elaboração_F4FA50B9.html"];
contentPage.processPage.elementUrls["_PbIHkEnXEeKxYpjLfq5O3A"] = ["Glossário","Help_Desk/deliveryprocesses/glossary_3ED52CCD.html"];
contentPage.processPage.elementUrls["_6e1wUUnVEeKxYpjLfq5O3A"] = ["Testador","Help_Desk/deliveryprocesses/tester_38848F95.html"];
contentPage.processPage.elementUrls["_wwbcMUnTEeKRYqO7-cZuww"] = ["Implementar a Solução","Help_Desk/deliveryprocesses/implement_solution_7C55E786.html"];
contentPage.processPage.elementUrls["_uD_EEUnTEeKRYqO7-cZuww"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_F76580E2.html"];
contentPage.processPage.elementUrls["_tYyK8UnTEeKRYqO7-cZuww"] = ["Integrar e Criar a Construção","Help_Desk/deliveryprocesses/integrate_and_create_build_D6717E71.html"];
contentPage.processPage.elementUrls["_gZPuMEnaEeK7uPdJ1lPx3Q"] = ["Integração de Modulos","Help_Desk/deliveryprocesses/integrar_modulos_B9BAB750.html"];
contentPage.processPage.elementUrls["_K_nlkUnXEeKxYpjLfq5O3A"] = ["Visão","Help_Desk/deliveryprocesses/vision_E965421E.html"];
contentPage.processPage.elementUrls["_YdUWQUnWEeKxYpjLfq5O3A"] = ["Arquiteto","Help_Desk/deliveryprocesses/architect_B53DECD2.html"];
contentPage.processPage.elementUrls["_-h5q1UmNEeKOcvRWZE27NA"] = ["Testar Solução","Help_Desk/deliveryprocesses/Testar Solução_B8ECC8DA.html"];
contentPage.processPage.elementUrls["_wwbcMknTEeKRYqO7-cZuww"] = ["Executar os Testes de Desenvolvedor","Help_Desk/deliveryprocesses/run_developer_tests_6AEEFB9C.html"];
contentPage.processPage.elementUrls["_KB41NUnbEeK7uPdJ1lPx3Q"] = ["Testador","Help_Desk/deliveryprocesses/tester_6D90C9C.html"];
contentPage.processPage.elementUrls["_YlVpckmMEeKOcvRWZE27NA"] = ["Refinar a Arquitetura","Help_Desk/deliveryprocesses/refine_the_architecture_11BAC693.html"];
contentPage.processPage.elementUrls["_Fc8DUEnbEeK7uPdJ1lPx3Q"] = ["Analista","Help_Desk/deliveryprocesses/analyst_3D7FF6BA.html"];
contentPage.processPage.elementUrls["_rnsAwEnTEeKRYqO7-cZuww"] = ["Projetar a Solução","Help_Desk/deliveryprocesses/design_solution_B0C81A95.html"];
contentPage.processPage.elementUrls["_aOpxAknWEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_7762C641.html"];
contentPage.processPage.elementUrls["_uD_rIEnTEeKRYqO7-cZuww"] = ["Executar os Testes","Help_Desk/deliveryprocesses/run_tests_2602583B.html"];
contentPage.processPage.elementUrls["_IGow0UnYEeK7uPdJ1lPx3Q"] = ["Teste de Desenvolvedor","Help_Desk/deliveryprocesses/developer_test_A5DE49A3.html"];
contentPage.processPage.elementUrls["_A_gEIEnaEeK7uPdJ1lPx3Q"] = ["Mitigar os Riscos","Help_Desk/deliveryprocesses/mitigar_riscos_2E2E3518.html"];
contentPage.processPage.elementUrls["_rqS980nVEeKGP5MA8koQEg"] = ["Testador","Help_Desk/deliveryprocesses/tester_C2EE6D90.html"];
contentPage.processPage.elementUrls["_nSCSUEnXEeKxYpjLfq5O3A"] = ["Construção","Help_Desk/deliveryprocesses/build_C9886747.html"];
contentPage.processPage.elementUrls["_hQtCAEnXEeKxYpjLfq5O3A"] = ["Cronograma","Help_Desk/deliveryprocesses/cronograma_A9225E3E.html"];
contentPage.processPage.elementUrls["_uTdGoknXEeKxYpjLfq5O3A"] = ["Registro de Teste","Help_Desk/deliveryprocesses/test_log_ABB16FA0.html"];
contentPage.processPage.elementUrls["_L98rIUmMEeKOcvRWZE27NA"] = ["Desenvolver a Arquitetura","Help_Desk/deliveryprocesses/Desenvolver a Arquitetura_4B6AFCF1.html"];
contentPage.processPage.elementUrls["_rqS98UnVEeKGP5MA8koQEg"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_6B7B83B5.html"];
contentPage.processPage.elementUrls["_I4xfYUmLEeKzbN0QdwCHdg"] = ["Identificar e Refinar os Requisitos","Help_Desk/deliveryprocesses/Identificar e Refinar os Requisitos_9A93AA4A.html"];
contentPage.processPage.elementUrls["_HnHfsUmKEeKu29KVoS-SOg"] = ["Iniciar o Projeto","Help_Desk/deliveryprocesses/p_4B782661.html"];
contentPage.processPage.elementUrls["_8shdkUmNEeKOcvRWZE27NA"] = ["Testar Solução","Help_Desk/deliveryprocesses/Testar Solução_47E25360.html"];
contentPage.processPage.elementUrls["_9FXtsUnVEeKxYpjLfq5O3A"] = ["Desenvolvedor","Help_Desk/deliveryprocesses/developer_2F5107AB.html"];
contentPage.processPage.elementUrls["_Kz5AQEnjEeKJs9Z4aVEEmA"] = ["Marco da Fase de Transição","Help_Desk/deliveryprocesses/Marco da Fase de Transição_24E23C72.html"];
contentPage.processPage.elementUrls["_un2o8UmNEeKOcvRWZE27NA"] = ["Iteração da Fase de Construção 1","Help_Desk/deliveryprocesses/Iteração da Fase de Construção 1_E7E1EED2.html"];
contentPage.processPage.elementUrls["_9FXtsEnVEeKxYpjLfq5O3A"] = ["Analista","Help_Desk/deliveryprocesses/analyst_24B3279B.html"];
contentPage.processPage.elementUrls["_KB41MEnbEeK7uPdJ1lPx3Q"] = ["Analista","Help_Desk/deliveryprocesses/analyst_37A94A6D.html"];
contentPage.processPage.elementUrls["__2jJk0mNEeKOcvRWZE27NA"] = ["Desenvolver um Incremento da Solução","Help_Desk/deliveryprocesses/Desenvolver um Incremento da Solução_D6D414D7.html"];
contentPage.processPage.elementUrls["__LViYEnaEeK7uPdJ1lPx3Q"] = ["Gerente de Projeto","Help_Desk/deliveryprocesses/project_manager_D5D47FEC.html"];
contentPage.processPage.elementUrls["_LD1hwEnYEeK7uPdJ1lPx3Q"] = ["Construção","Help_Desk/deliveryprocesses/build_674ECA35.html"];
contentPage.processPage.elementUrls["_-h5q00mNEeKOcvRWZE27NA"] = ["Desenvolver um Incremento da Solução","Help_Desk/deliveryprocesses/Desenvolver um Incremento da Solução_4BCDD096.html"];
contentPage.processPage.elementUrls["_fIyQEEnTEeK1i6L3TaQ98w"] = ["Implementar os Scripts de Teste","Help_Desk/deliveryprocesses/implement_test_scripts_92E0A6EE.html"];
contentPage.processPage.elementUrls["_MVPfQEnYEeK7uPdJ1lPx3Q"] = ["Caso de Teste","Help_Desk/deliveryprocesses/test_case_1432694B.html"];
contentPage.processPage.elementUrls["__LU7UEnaEeK7uPdJ1lPx3Q"] = ["Qualquer Papel","Help_Desk/deliveryprocesses/any_role_B0A4095F.html"];
contentPage.processPage.elementUrls["_3rOZMUnVEeKxYpjLfq5O3A"] = ["Projetar a Solução","Help_Desk/deliveryprocesses/design_solution_FCD2D292.html"];
