<?php
require_once "../../lib/Conection.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 01:53:08.
 */
class ConectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Conection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Conection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }
    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
       }
    /**
     * @covers Conection::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
