<?php

require_once "../../DAO/ChamadoDAO.php";
require_once "../../Model/Chamado.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 14:55:28.
 */
class ChamadoDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ChamadoDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ChamadoDAO();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }


    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
    }
    /**
     * @covers ChamadoDAO::inserirChamado
     * @todo   Implement testInserirChamado().
     */
    public function testInserirChamado() {
        $chamado = new Chamado('descricao', 'solicitante', 1, 'tipoChamado', 'local_equipamento', 'equip_patrimonio');
        $resultado=  $this->object->inserirChamado($chamado);
        $this->assertNotNull($resultado);
    }

    /**'
     * @covers ChamadoDAO::alterarChamado
     * @todo   Implement testAlterarChamado().
     */
    public function testAlterarChamado() {
        
        $resultado= $this->object->alterarChamado(2, NULL, 2);
        $this->assertTrue(true, $resultado, "Nao foi possivel alterar O status!");
    }

    /**
     * @covers ChamadoDAO::obterChamadoPorStatus
     * @todo   Implement testObterChamadoPorStatus().
     */
    public function testObterChamadoPorStatus() {
        $resultado = $this->object->obterChamadoPorStatus(2);
        $this->assertTrue(true, $resultado, "Nao foi possivel alterar O status!");
    }

    /**
     * @covers ChamadoDAO::obterChamado_Especifico
     * @todo   Implement testObterChamado_Especifico().
     */
    public function testObterChamado_Especifico() {
        $resultado = $this->object->obterChamado_Especifico(2);
        $this->assertTrue(true, $resultado, "Nao foi possivel alterar O status!");
    }

    /**
     * @covers ChamadoDAO::obterChamado_Geral
     * @todo   Implement testObterChamado_Geral().
     */
    public function testObterChamado_Geral() {
        $resultado = $this->object->obterChamado_Geral();
       foreach($resultado as $row){
            $this->assertArrayHasKey("cod", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("tipo_cod", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("usuario_login", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("descricao", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("data_inicial", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("data_final", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("patrimonio_equip", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("localizacao_equip", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("login_tecnico", $row, "Nao foi possivel retornar todos os campos!");
            $this->assertArrayHasKey("status_cod", $row, "Nao foi possivel retornar todos os campos!");
        }
    }

    /**
     * @covers ChamadoDAO::deletarChamado
     * @todo   Implement testDeletarChamado().
     */
    public function testDeletarChamado() {
        $resultado = $this->object->deletarChamado(2);
        $this->assertTrue(true, $resultado, "Impossivel deletar chamado!");
    }

    /**
     * @covers ChamadoDAO::fechaConexão
     * @todo   Implement testFechaConexão().
     */
    public function testFechaConexão() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
