<?php
require_once '..\..\DAO\UsuarioDAO.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:40:11.
 */
class UsuarioDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UsuarioDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UsuarioDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testVerificar() {
        // Remove the following lines when you implement this test.
        $this->assertNotNull($this->object);
    }
}
