<?php
require_once "../../Model/Chamado.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:06.
 */
class ChamadoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Chamado
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Chamado('descricao', 'solicitante', 'status', 'tipoChamado', 'local_equipamento', 'equip_patrimonio');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers Chamado::getLocal_equipamento
     * @todo   Implement testGetLocal_equipamento().
     */
    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
    }
    public function testGetLocal_equipamento() {
        
        $resultado = $this->object->getLocal_equipamento();
        $this->assertEquals($resultado,'local_equipamento');
    }

    /**
     * @covers Chamado::setLocal_equipamento
     * @todo   Implement testSetLocal_equipamento().
     */
    public function testSetLocal_equipamento() {
        $this->object->setLocal_equipamento('equipamento');
        $resultado = $this->object->getLocal_equipamento();
        $this->assertEquals($resultado,'equipamento');
    }

    /**
     * @covers Chamado::getEquip_patrimonio
     * @todo   Implement testGetEquip_patrimonio().
     */
    public function testGetEquip_patrimonio() {
        $resultado = $this->object->getEquip_patrimonio();
        $this->assertEquals($resultado,'equip_patrimonio');
    }

    /**
     * @covers Chamado::setEquip_patrimonio
     * @todo   Implement testSetEquip_patrimonio().
     */
    public function testSetEquip_patrimonio() {
        $this->object->setEquip_patrimonio('patrimonio');
        $resultado = $this->object->getEquip_patrimonio();
        $this->assertEquals($resultado,'patrimonio');
    }

    /**
     * @covers Chamado::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
        
        $resultado = $this->object->getCodigo();
        $this->assertEquals($resultado,NULL);
    }

    /**
     * @covers Chamado::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        $this->object->setCodigo('codigos');
        $resultado = $this->object->getCodigo();
        $this->assertEquals($resultado,'codigos');
    }

    /**
     * @covers Chamado::getData_inicial
     * @todo   Implement testGetData_inicial().
     */
    public function testGetData_inicial() {
        $resultado = $this->object->getData_inicial();
        $this->assertEquals($resultado,NULL);
    }

    /**
     * @covers Chamado::setData_inicial
     * @todo   Implement testSetData_inicial().
     */
    public function testSetData_inicial() {
        $this->object->setData_inicial('data');
        $resultado = $this->object->getData_inicial();
        $this->assertEquals($resultado,'data');
    }

    /**
     * @covers Chamado::getData_final
     * @todo   Implement testGetData_final().
     */
    public function testGetData_final() {
        $resultado = $this->object->getData_final();
        $this->assertEquals($resultado,NULL);
    }

    /**
     * @covers Chamado::setData_final
     * @todo   Implement testSetData_final().
     */
    public function testSetData_final() {
        $this->object->setData_final('data');
        $resultado = $this->object->getData_final();
        $this->assertEquals($resultado,'data');
    }

    /**
     * @covers Chamado::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao() {
        
        $resultado = $this->object->getDescricao();
        $this->assertEquals($resultado,'descricao');
    }

    /**
     * @covers Chamado::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao() {
        $this->object->setDescricao('descricoes');
        $resultado = $this->object->getDescricao();
        $this->assertEquals($resultado,'descricoes');
    }

    /**
     * @covers Chamado::getSolicitante
     * @todo   Implement testGetSolicitante().
     */
    public function testGetSolicitante() {
        
        $resultado = $this->object->getSolicitante();
        $this->assertEquals($resultado,'solicitante');
    }

    /**
     * @covers Chamado::setSolicitante
     * @todo   Implement testSetSolicitante().
     */
    public function testSetSolicitante() {
        $this->object->setSolicitante('usuario');
        $resultado = $this->object->getSolicitante();
        $this->assertEquals($resultado,'usuario');
    }

    /**
     * @covers Chamado::getTecnico
     * @todo   Implement testGetTecnico().
     */
    public function testGetTecnico() {
        
        $resultado = $this->object->getTecnico();
        $this->assertEquals($resultado,NULL);
    }

    /**
     * @covers Chamado::setTecnico
     * @todo   Implement testSetTecnico().
     */
    public function testSetTecnico() {
        $this->object->setTecnico('tecnicos');
        $resultado = $this->object->getTecnico();
        $this->assertEquals($resultado,'tecnicos');
    }

    /**
     * @covers Chamado::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        
        $resultado = $this->object->getStatus();
        $this->assertEquals($resultado,'status');
    }

    /**
     * @covers Chamado::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        $this->object->setStatus('em aberto');
        $resultado = $this->object->getStatus();
        $this->assertEquals($resultado,'em aberto');
    }

    /**
     * @covers Chamado::getSolucao
     * @todo   Implement testGetSolucao().
     */
    public function testGetSolucao() {
        
        $resultado = $this->object->getSolucao();
        $this->assertEquals($resultado,NULL);
    }

    /**
     * @covers Chamado::setSolucao
     * @todo   Implement testSetSolucao().
     */
    public function testSetSolucao() {
        $this->object->setSolucao('reiniciar');
        $resultado = $this->object->getSolucao();
        $this->assertEquals($resultado,'reiniciar');
    }

    /**
     * @covers Chamado::getTipoChamado
     * @todo   Implement testGetTipoChamado().
     */
    public function testGetTipoChamado() {
        
        $resultado = $this->object->getTipoChamado();
        $this->assertEquals($resultado,'tipoChamado');
    }

    /**
     * @covers Chamado::setTipoChamado
     * @todo   Implement testSetTipoChamado().
     */
    public function testSetTipoChamado() {
        $this->object->setTipoChamado('tipo_Chamado');
        $resultado = $this->object->getTipoChamado();
        $this->assertEquals($resultado,'tipo_Chamado');
    }

}
