<?php
require_once "../../Model/Solucao.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:06.
 */
class SolucaoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Solucao
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Solucao(1, 'descricao', '01-01-2013');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }
    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
       }
    /**
     * @covers Solucao::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
       
       $resultado = $this->object->getCodigo();
       $this->assertEquals($resultado, 1);
    }

    /**
     * @covers Solucao::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        // Remove the following lines when you implement this test.
        $this->object->setCodigo(2);
        $resultado = $this->object->getCodigo();
        $this->assertEquals($resultado,2);
    }

    /**
     * @covers Solucao::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao() {
       $resultado = $this->object->getDescricao();
       $this->assertEquals($resultado, 'descricao');
    }

    /**
     * @covers Solucao::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao() {
        // Remove the following lines when you implement this test.
        $this->object->setDescricao('em aberto');
        $resultado = $this->object->getDescricao();
        $this->assertEquals($resultado,'em aberto');
    }

    /**
     * @covers Solucao::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $resultado = $this->object->getData();
        $this->assertEquals($resultado,'01-01-2013');
    }

    /**
     * @covers Solucao::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->object->setData('02-02-1013');
        $resultado = $this->object->getData();
        $this->assertEquals($resultado,'02-02-1013');
    }

}
