<?php
require_once "../../Model/Tipo_Chamado.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:08.
 */
class Tipo_ChamadoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Tipo_Chamado
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tipo_Chamado('codigo', 'descricao');
    }

    protected function tearDown() {
        unset($this->object);
    }

    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
    }

    /**
     * @covers Tipo_Chamado::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
        $resultado=$this->object->getCodigo();
        $this->assertEquals($resultado, 'codigo');
    }

    /**
     * @covers Tipo_Chamado::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        $this->object->setCodigo(1);
        $resultado=$this->object->getCodigo();
        $this->assertEquals($resultado, 1);
    }

    /**
     * @covers Tipo_Chamado::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao() {
        $resultado=$this->object->getDescricao();
        $this->assertEquals($resultado, 'descricao');
    }

    /**
     * @covers Tipo_Chamado::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao() {
        $this->object->setDescricao('software');
        $resultado=  $this->object->getDescricao();
        $this->assertEquals($resultado, 'software');
    }

}
