<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:08.
 */
class Tipo_ChamadoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Tipo_Chamado
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tipo_Chamado;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Tipo_Chamado::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tipo_Chamado::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tipo_Chamado::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tipo_Chamado::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
