<?php
require_once "../../Model/Usuario.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:07.
 */
class UsuarioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Usuario
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Usuario('codigo', 'login', 'senha', 'nome', 'email', 'matricula');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }
    public function testConstrutor() {
        $resultado = $this->object;
        $this->assertNotNull($resultado);
    }

    /**
     * @covers Usuario::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
       $resultado = $this->object->getCodigo();
       $this->assertEquals($resultado, 'codigo');
    }

    /**
     * @covers Usuario::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        $this->object->setCodigo(1);
        $resultado = $this->object->getCodigo();
       $this->assertEquals($resultado, 1);
    }

    /**
     * @covers Usuario::getLogin
     * @todo   Implement testGetLogin().
     */
    public function testGetLogin() {
       $resultado = $this->object->getLogin();
       $this->assertEquals($resultado, 'login');
    }

    /**
     * @covers Usuario::setLogin
     * @todo   Implement testSetLogin().
     */
    public function testSetLogin() {
        $this->object->setLogin('lucas');
       $resultado = $this->object->getLogin();
       $this->assertEquals($resultado, 'lucas');
    }

    /**
     * @covers Usuario::getSenha
     * @todo   Implement testGetSenha().
     */
    public function testGetSenha() {
        $resultado = $this->object->getSenha();
       $this->assertEquals($resultado, 'senha');
    }

    /**
     * @covers Usuario::setSenha
     * @todo   Implement testSetSenha().
     */
    public function testSetSenha() {
        $this->object->setSenha('123456');
       $resultado = $this->object->getSenha();
       $this->assertEquals($resultado, '123456');
    }

    /**
     * @covers Usuario::getNome
     * @todo   Implement testGetNome().
     */
    public function testGetNome() {
        $resultado = $this->object->getNome();
       $this->assertEquals($resultado, 'nome');
    }

    /**
     * @covers Usuario::setNome
     * @todo   Implement testSetNome().
     */
    public function testSetNome() {
       $this->object->setNome('Lucas') ;
       $resultado = $this->object->getNome();
       $this->assertEquals($resultado, 'Lucas');
    }

    /**
     * @covers Usuario::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
       $resultado = $this->object->getEmail();
       $this->assertEquals($resultado, 'email');
    }

    /**
     * @covers Usuario::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail() {
        $this->object->setEmail('couto@mail');
       $resultado = $this->object->getEmail();
       $this->assertEquals($resultado, 'couto@mail');
    }

    /**
     * @covers Usuario::getMatricula
     * @todo   Implement testGetMatricula().
     */
    public function testGetMatricula() {
       $resultado = $this->object->getMatricula();
       $this->assertEquals($resultado, 'matricula');
    }

    /**
     * @covers Usuario::setMatricula
     * @todo   Implement testSetMatricula().
     */
    public function testSetMatricula() {
        $this->object->setMatricula('100131182');
        $resultado = $this->object->getMatricula();
       $this->assertEquals($resultado, '100131182');
    }

}
