<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 16:03:07.
 */
class UsuarioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Usuario
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Usuario;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Usuario::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setCodigo
     * @todo   Implement testSetCodigo().
     */
    public function testSetCodigo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::getLogin
     * @todo   Implement testGetLogin().
     */
    public function testGetLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setLogin
     * @todo   Implement testSetLogin().
     */
    public function testSetLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::getSenha
     * @todo   Implement testGetSenha().
     */
    public function testGetSenha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setSenha
     * @todo   Implement testSetSenha().
     */
    public function testSetSenha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::getNome
     * @todo   Implement testGetNome().
     */
    public function testGetNome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setNome
     * @todo   Implement testSetNome().
     */
    public function testSetNome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::getMatricula
     * @todo   Implement testGetMatricula().
     */
    public function testGetMatricula() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Usuario::setMatricula
     * @todo   Implement testSetMatricula().
     */
    public function testSetMatricula() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
